
package:
  name: driftmlp
  version: 1.01

source:
  git_rev:
  git_url: https://github.com/MikeOMa/DriftMLP

requirements:
  build:
    - python
    - setuptools
    - geopandas
    - numpy>=1.17,<=1.20
    - cartopy
    - matplotlib
    - h3-py
    - python-igraph
    - folium
    - pyproj>=2.2.0
    - numba
  run:
    - python

test:
  imports:
    - pytest

about:
  home:
